version: "3.9"

services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    command: ["-conf", "/Corefile"]

    ports:
      - "127.0.0.1:5353:53/udp"
      - "127.0.0.1:5353:53/tcp"

    volumes:
      - ./zones:/zones:ro
      - ./Corefile:/Corefile:ro

    restart: unless-stopped
