apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-1
  namespace: gateway-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app-1
  template:
    metadata:
      labels:
        app: backend-app-1
    spec:
      containers:
        - name: backend-app-1
          image: ananth98/sample_backend_app1:1.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: backend-app-1-service
  namespace: gateway-api
spec:
  selector:
    app: backend-app-1
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP