apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-2
  namespace: gateway-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app-2
  template:
    metadata:
      labels:
        app: backend-app-2
    spec:
      containers:
        - name: backend-app-2
          image: ananth98/sample_backend_app2:1.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5001

---

apiVersion: v1
kind: Service
metadata:
  name: backend-app-2-service
  namespace: gateway-api
spec:
  selector:
    app: backend-app-2
  ports:
    - port: 80
      targetPort: 5001
  type: ClusterIP